/// Controls which widget types appear in the captured tree.
class LomTreeConfig {
  final Set<String> pruneAt;
  final Set<String> ignoreAt;
  final Set<String> noiseAt;
  final Set<String> semantics;

  const LomTreeConfig({
    this.pruneAt = const {'SnapshotWidget', 'BlockSemantics'},
    this.ignoreAt = const {
      'Semantics',
      'Listener',
      'Pointer',
      'Controller',
      'Scope',
      'Clip',
      'Focus',
      'Navigator',
      'Overlay',
      'Model',
      'Transition',
      'Offstage',
      'Mouse',
      'Transform',
      'Viewport',
      'Layout',
      'Overflow',
    },
    this.noiseAt = const {
      'Padding',
      'Center',
      'Column',
      'Stack',
      'Row',
      'SizedBox',
      'Align',
      'Expanded',
      'Flexible',
      'Container',
      'FittedBox',
      'ConstrainedBox',
      'LimitedBox',
      'DecoratedBox',
      'ColoredBox',
      'RepaintBoundary',
      'SafeArea',
      'FractionallySizedBox',
      'IgnorePointer',
      'AbsorbPointer',
      'TapRegion',
      'RawGestureDetector',
      'MetaData',
      'PhysicalModel',
      'AnimatedPhysicalModel',
      'PhysicalShape',
      'CustomPaint',
      'TextFieldTapRegion',
      'ExcludeSemantics',
      'ImageFiltered',
      'TextFormField',
    },
    this.semantics = const {
      'TextField',
      'TextFormField',
      'ElevatedButton',
      'TextButton',
      'OutlinedButton',
      'IconButton',
      'Card',
      'Switch',
      'Checkbox',
      'InkWell',
      'GestureDetector',
      'Image',
      'Icon',
    },
  });
}
