const Set<String> widgetsToIgnore = {
  'SnapshotWidget',
  'ConstrainedBox',
  'PhysicalShape',
  'LimitedBox',
  'TapRegion',
  'DecoratedBox',
  'SizeChangedLayoutNotifier',
  'RepaintBoundary',
  'CustomPaint',
  'CustomMultiChildLayout',
  // 'Padding',
  // 'LayoutBuilder',
  // 'Center',
  // 'Align',
  // 'RichText',
  // 'Padding',
  // 'Stack',
  // 'Row',
  // 'Column',
  // 'SizedBox',
};

const List<String> widgetsToIgnoreIfContains = [
  'Semantics',
  'Listener',
  'Pointer',
  'Controller',
  'Scope',
  'Clip',
  'Focus',
  'Navigator',
  'Overlay',
  'Model',
  'Transition',
  'Offstage',
  'Mouse',
  'TextField',
  'Transform',
];
