const Set<String> widgetsToIgnore = {
  'SnapshotWidget',
  'ConstrainedBox',
  'PhysicalShape',
  'LimitedBox',
  'TapRegion',
  'DecoratedBox',
  'RepaintBoundary',
  'CustomPaint',
  'MetaData',
  'ColoredBox',
};

const List<String> widgetsToIgnoreIfContains = [
  'Semantics',
  'Listener',
  'Pointer',
  'Controller',
  'Scope',
  'Clip',
  'Focus',
  'Navigator',
  'Overlay',
  'Model',
  'Transition',
  'Offstage',
  'Mouse',
  'TextField',
  'Transform',
  'Image',
  'Viewport',
  'Layout',
  'Overflow',
  'Align',
];
